# Generated by Django 2.2.20 on 2021-06-04 18:13

from django.db import migrations, models
import openedx.core.djangoapps.content.course_overviews.data


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0024_overview_adds_has_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='certificates_display_behavior',
            field=models.TextField(choices=[('early_no_info', 'EARLY_NO_INFO'), ('end', 'END'), ('end_with_date', 'END_WITH_DATE')], default=openedx.core.djangoapps.content.course_overviews.data.CertificatesDisplayBehaviors('early_no_info'), null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourseoverview',
            name='certificates_display_behavior',
            field=models.TextField(choices=[('early_no_info', 'EARLY_NO_INFO'), ('end', 'END'), ('end_with_date', 'END_WITH_DATE')], default=openedx.core.djangoapps.content.course_overviews.data.CertificatesDisplayBehaviors('early_no_info'), null=True),
        ),
    ]
