# Generated by Django 2.2.20 on 2021-06-10 19:08

from django.db import migrations, models
import xmodule.data


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0024_overview_adds_has_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='certificates_display_behavior',
            field=models.TextField(choices=[('end', 'END'), ('end_with_date', 'END_WITH_DATE'), ('early_no_info', 'EARLY_NO_INFO')], default=xmodule.data.CertificatesDisplayBehaviors('early_no_info'), null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourseoverview',
            name='certificates_display_behavior',
            field=models.TextField(choices=[('end', 'END'), ('end_with_date', 'END_WITH_DATE'), ('early_no_info', 'EARLY_NO_INFO')], default=xmodule.data.CertificatesDisplayBehaviors('early_no_info'), null=True),
        ),
    ]
