# Generated by Django 2.2.24 on 2021-09-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0024_overview_adds_has_highlights'),
        ('course_overviews', '0012_courseoverviewexpansion_eng_display_name'),
    ]

    operations = [
    ]
