# Generated by Django 2.2.24 on 2021-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0025_merge_20210930_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverviewexpansion',
            name='eng_display_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='courseoverviewexpansion',
            name='vertical_cover_path',
            field=models.TextField(blank=True, default=''),
        ),
    ]
