# Generated by Django 3.2.13 on 2022-04-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0025_auto_20210702_1602'),
        ('course_overviews', '0026_auto_20210930_1214'),
    ]

    operations = [
    ]
