#!/bin/bash

docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME --build-arg EDX_PLATFORM_REPOSITORY=$EDX_PLATFORM_REPOSITORY --build-arg EDX_PLATFORM_VERSION=$SOURCE_BRANCH --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from uetuluk/openedx:maple.rc4 .