# Generated by Django 2.2.24 on 2021-11-16 05:32

from django.db import migrations
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_userretirementpartnerreportingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursetag',
            name='course_id',
            field=opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255),
        ),
    ]
