# Generated by Django 2.2.24 on 2021-11-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_setting', '0002_auto_20190104_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannersetting',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bannersetting',
            name='url_path',
            field=models.TextField(blank=True, default=''),
        ),
    ]
