# Generated by Django 2.2.24 on 2021-09-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_squashed_0031_auto_20200317_1122'),
        ('student', '0042_userextension'),
    ]

    operations = [
    ]
