# Generated by Django 3.2.13 on 2022-04-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0043_merge_20210930_1122'),
        ('student', '0043_remove_userprofile_allow_certificate'),
    ]

    operations = [
    ]
